# Generated by Django 4.0.3 on 2022-06-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('dvRut', models.CharField(max_length=1)),
                ('nombreFantasia', models.CharField(max_length=30)),
                ('razonSocial', models.CharField(max_length=100)),
                ('giro', models.IntegerField()),
                ('direccionCasaMatriz', models.CharField(max_length=100)),
                ('direccionFacturacion', models.CharField(max_length=100)),
                ('correoContacto', models.EmailField(max_length=254)),
                ('telefonoContacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPedido', models.IntegerField()),
                ('codProducto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=50)),
                ('precioProducto', models.IntegerField()),
                ('subtotalPedido', models.IntegerField()),
                ('fechaEntrega', models.DateField()),
                ('estadoEntrega', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='estadoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='estadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='giro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPedido', models.IntegerField()),
                ('fechaPedido', models.DateField()),
                ('fechaPago', models.DateField()),
                ('tipoPedido', models.IntegerField()),
                ('codFactura', models.IntegerField()),
                ('totalPedido', models.IntegerField()),
                ('estadoPedido', models.IntegerField()),
                ('codCliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('fechaIncorporacion', models.DateField()),
                ('idProveedor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('dvRut', models.CharField(max_length=1)),
                ('nombreFantasia', models.CharField(max_length=30)),
                ('razonSocial', models.CharField(max_length=100)),
                ('giro', models.IntegerField()),
                ('direccionCasaMatriz', models.CharField(max_length=100)),
                ('correoContacto', models.EmailField(max_length=254)),
                ('telefonoContacto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
    ]
