# Generated by Django 4.0.3 on 2022-06-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('suscripcion', models.BooleanField()),
            ],
        ),
    ]
