# Generated by Django 4.0.3 on 2022-06-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioDcto',
            field=models.IntegerField(default=0),
        ),
    ]
