# Generated by Django 4.0.3 on 2022-06-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0003_producto_preciodcto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='rutaImg',
            field=models.CharField(default='ruta', max_length=500),
        ),
    ]
