# Generated by Django 4.0.3 on 2022-06-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0004_producto_rutaimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tamano',
            field=models.IntegerField(default=0),
        ),
    ]
