# Generated by Django 4.0.3 on 2022-06-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedatos', '0006_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='logueado',
            field=models.BooleanField(default=0),
        ),
    ]
